dataset:
  name: "amazon_electronic"
  num_users: 1435
  num_items: 1522
  interactions: 35931

  implicit: true
  split: "leave_one_out"

  path_raw: "data/raw/amazon_electronic/"
  path_processed: "data/processed/amazon_electronic/"
