dataset:
  name: "steam"
  num_users: 3753
  num_items: 5134
  interactions: 114713

  implicit: true
  split: "leave_one_out"

  path_raw: "data/raw/steam_200k/"
  path_processed: "data/processed/steam_200k/"
