dataset:
  name: "ml_100k"
  num_users: 943
  num_items: 1682
  interactions: 100000

  implicit: true
  split: "leave_one_out"

  path_raw: "data/raw/movielens_100k/"
  path_processed: "data/processed/movielens_100k/"
