dataset:
  name: "ml_1m"
  num_users: 6040
  num_items: 3706
  interactions: 1000209

  implicit: true
  split: "leave_one_out"

  min_interactions: 1
  path_raw: "data/raw/movielens_1m/"
  path_processed: "data/processed/movielens_1m/"
